[package]
name = "rust_test_uwu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winconsole = "0.11.1"
rand = "0.8.4"

[[bin]]
name = "rust_test_uwu"
